### ISSUE TITLE
Font size control of ENTRY

### ISSUE THREAD

**Issue by biooo** [syui/hugo-theme-air#12]
Very nice theme; however, it seems you stop developing it. Two questions
1) Is it possile to enlarge the font size of title (e.g. HUGO THEME AIR) through customizing some specific parameters? 
2) Any plan to implement a navigation bar (e.g. HOME, ABOUT etc) on the header . Thanks.

**Comment by syui** [comment]
1. yes 

```css
.page-title {
    font-size: 6rem;
}
```

2. example

```html
<header id="header">
  <div id="header-main" class="header-inner">
    <div class="outer">

	<nav class="navbar navbar-default">
	  <div class="container-fluid">

    {{ partial "title" . }}

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
    {{ partial "navbar-menu" . }}
      </ul>
    </div>
  </div>
</nav>
</header>
```

> navbar-menu.html

```html
   <li><a href="#">Home</a></li>
   <li><a href="#">About</a></li>
```

**Comment by biooo** [comment]
Thanks for your suggestion.

1. On the line 1770 of the file "screen.css", I changed the script as
 .page-title {
        font-size: 30rem;
    }

The font size has no change on the web page.

2. Tried to incorporate your code in the layouts/index.html, it does not work. Please can you provide more clues. Many thanks !

**Comment by syui** [comment]
@biooo use bootstrap.
https://getbootstrap.com/docs/4.1/components/navbar/

**Comment by biooo** [comment]
Hi Syui.

Thanks for your suggestion.
I tried to incorporate your suggestion on your theme and casper theme. The navigation menu is working fine now; however, there is no effect of particles animation. Scripts please see: 
 https://github.com/biooo/air

Any suggestion. Thanks.

**Comment by syui** [comment]
Hi, It's Very nice theme.

**Comment by biooo** [comment]
(1) I put these lines at the end of the "screen.css"
<pre>
/* ---- stats.js ---- */

.count-particles {
  background: #000022;
  position: absolute;
  top: 48px;
  left: 0;
  width: 80px;
  color: #13E8E9;
  font-size: .8em;
  text-align: left;
  text-indent: 4px;
  line-height: 14px;
  padding-bottom: 2px;
  font-family: Helvetica, Arial, sans-serif;
  font-weight: bold;
}

.js-count-particles {
  font-size: 1.1em;
}

#stats,
.count-particles {
  -webkit-user-select: none;
  margin-top: 5px;
  margin-left: 5px;
}

#stats {
  border-radius: 3px 3px 0 0;
  overflow: hidden;
}

.count-particles {
  border-radius: 0 0 3px 3px;
}
</pre>

(2) put "particles.min.js" in "static/js/" and inserted ines in "layouts/partials/header.html" as follows
<pre>
<script src="{{ .Site.BaseURL }}js/particles.min.js"></script>
<script src="{{ .Site.BaseURL }}js/particles.js"></script> 
</pre>

The menu on the navigation bar  is working. However, there is no particle animation on the main page. Any solution? Thanks very much for your help!

**Comment by syui** [comment]
### make particles

https://vincentgarreau.com/particles.js/ -> code pen -> copy & paste (html,css,js) -> html head link

### error check

chrome -> alt + command + i (dev mode) -> click X(red)

get error message.
