### ISSUE TITLE
navigation bar

### ISSUE THREAD

**Issue by biooo** [syui/hugo-theme-air#13]
Hi I also tested this navigation bar. If you click the menu and go to the next page, the navigation bar will heavily cover the header of the linked page (see image enclosed). It does not seem to be a good solution. Any suggestion. Thanks.

![screen shot 2019-02-24 at 21 16 28](https://user-images.githubusercontent.com/38316570/53305506-3ea9ed00-387a-11e9-882a-729f2ce5888d.png)

_Originally posted by @biooo in https://github.com/syui/hugo-theme-air/issues/7#issuecomment-466818385_

**Comment by syui** [comment]
thx, fixed.
