### ISSUE TITLE
How to change logo in Air theme?

### ISSUE THREAD

**Issue by VictorCarreira** [syui/hugo-theme-air#17]
Dear Syui,
Firstly I would like to say thank you for your work. I would like to know how can I change the eagle logo on Air-theme, in the config.toml file? What it will be the procedure? 
I hope to hearing from you soon,
Thanks again.
Victor Carreira

**Comment by syui** [comment]
Replace `static/images/user.png` with myfile.

You can also change the location.

> config.toml

```toml
[params]
  logo = "images/user.png"
```

```html
{{.Site.Params.logo}}
```

**Comment by VictorCarreira** [comment]
Actually I've already tried that and comes an issue as you can see in the image bellow. 

![Captura de tela de 2019-12-15 23-12-28](https://user-images.githubusercontent.com/5520827/70874436-df47d580-1f90-11ea-80ad-5a3f84c81e21.png)

**Comment by VictorCarreira** [comment]
config.toml configuration ... 

`BaseUrl= "https://syui.cf/hugo-theme-air/"
LanguageCode= "en-US"
Title= "A EAGE-SEG Student Chapter"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2020"
canonifyurls = true

[author]
  name = "syui"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "The National Observatory Green Stone Belt website brings out the latest information about EAGE-SEG Student Chapters activities."
  cover = "images/user.png"
  author = "syui"
  authorlocation = ""
  authorwebsite = "https://syui.cf/hugo-theme-air/"
  bio= "my bio"
  logo = "images/logoSC.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = ""
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  mainSections = ["post"]`

**Comment by VictorCarreira** [comment]
About replacing the "user.png" file does not work too. Insted the eagle logo continues.

**Comment by syui** [comment]
```toml
BaseUrl= "https://localhost/"

[params]
  authorwebsite = "https://localhost"
  cover = "images/user.jpg"
  logo = "images/user.png"
```

 point : last slash `/`

**Comment by VictorCarreira** [comment]
Did not work the last slash either. I did not found the "user.jpg" in the static/images ...  

BaseUrl= "https://syui.cf/hugo-theme-air/"
LanguageCode= "en-US"
Title= "A EAGE-SEG Student Chapter"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2020"
canonifyurls = true

[author]
  name = "syui"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "The National Observatory Green Stone Belt website brings out the latest information about EAGE-SEG Student Chapters activities."
  cover = "images/user.jpg"
  author = "syui"
  authorlocation = ""
  authorwebsite = "https://syui.cf/hugo-theme-air"
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = ""
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  mainSections = ["post"]

**Comment by syui** [comment]
Please close the browser and rerun hugo server.

**Comment by VictorCarreira** [comment]
I've already tried that. Did work too. 
I am using netifly to run the site with hugo. Do you think it could be a problem concerning netifly?

**Comment by syui** [comment]
No, I think the problem with this theme and hugo.
