### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by mattermatician** [syui/hugo-theme-air#19]
Thank you for the nice theme. I am trying to create a main menu with a hamburger symbol.

Using Hugo v0.54.0

In config.toml I have several menu items like:
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 2

In about.md (metadata) I set accordingly:
     menu = "main"  

In hugo-theme-air/layouts/index.html I uncommented
    {{ if .Site.Menus.main }} 

This still yields only a hamburger symbol but no menu items are shown.

**Comment by syui** [comment]
edit `layout/partials/navigation.html`.

```html
<div class="nav">
    <h3 class="nav-title">Menu</h3>
    <a href="#" class="nav-close">
        <span class="hidden">Close</span>
    </a>
    <ul>
        {{ $currentNode := . }}
        {{ range .Site.Menus.main }}
            {{.Pre}}
            <li class="nav-opened{{if $currentNode.IsMenuCurrent "main" . }} nav-current{{end}}" role="presentation">
            	<a href="{{.URL}}">{{.Name}}</a>
            </li>
        {{end}}
    </ul>
    
    {{ if .Site.Params.RSSLink}}
    <a class="subscribe-button icon-feed" href="{{.Site.Params.RSSLink }}">Subscribe</a> </div>
    {{else}}
    <a class="subscribe-button icon-feed" href="{{if .IsNode}}{{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}{{else}}{{ .Site.BaseURL }}index.xml{{end}}">Subscribe</a>
    {{end}}
</div>
<span class="nav-cover"></span>
```

In some cases, remove the if `.Site.Menus.main` condition.

**Comment by syui** [comment]
@mattermatician 

sorry, edit `static/css/screen.css`.

```css
.nav {
    /* position: fixed; */
}
```

can you adjust this area?

**Comment by syui** [comment]
It seems that particles.js and menu are difficult to use together.

**Comment by syui** [comment]
it's done. remove the `position` of the `.main-nav.overlay` .

```css
.main-nav.overlay {
    /* position: absolute; */
}

.nav {
    position: fixed;
}
```

**Comment by syui** [comment]
Thanks for reporting the problem.

**Comment by syui** [comment]
The code for the main menu to work can be found in branch:menu.

```sh
$ git checkout menu
$ hugo serve
```
