### ISSUE TITLE
First post not formatted correctly

### ISSUE THREAD

**Issue by lowpro** [syui/hugo-theme-air#2]
I just started using this theme, and when I run hugo server -t hugo-theme-air after creating a post, it shows this:
![screenshot 1](https://cloud.githubusercontent.com/assets/12025954/9179322/b76fe112-3f69-11e5-8a02-1c380ffa8c07.png)
screenshot 2: (https://gyazo.com/2ff69c4440ec0cbe3130da08c9e6e774.png)

I'm not sure if this belongs here, but I could not find any answers. If I should change settings or mess with a certain file please let me know.

Google Translate:

私はこのテーマを使用して開始し、私はヒューゴサーバー-tポストを作成した後ヒューゴ·テーマ空気を実行すると、この例を示します。
![screenshot 1](https://cloud.githubusercontent.com/assets/12025954/9179322/b76fe112-3f69-11e5-8a02-1c380ffa8c07.png)
screenshot 2: (https://gyazo.com/2ff69c4440ec0cbe3130da08c9e6e774.png)

これはここに属している場合、私はわからないんだけど、私はすべての答えを見つけることができませんでした。私は特定のファイルに設定や混乱を変更する必要がある場合は私に知らせてください。

**Comment by syui** [comment]
Site top will fill the screen.

![](https://raw.githubusercontent.com/syui/hugo-theme-air/master/images/screenshot.png)

When you scroll down and read the article.

1. Please put the article in the test.

> /content/post/foo.md

```md
+++
author = "lowpro"
comments = false
date = "2015-01-01T00:00:00+00:00"
draft = false
image = ""
menu = ""
share = false
slug = "profile"
title= "First post not formatted correctly"
+++

I just started using this theme, and when I run hugo server -t hugo-theme-air after creating a post, it shows this:

![screenshot 1](https://cloud.githubusercontent.com/assets/12025954/9179322/b76fe112-3f69-11e5-8a02-1c380ffa8c07.png)

screenshot 2: (https://gyazo.com/2ff69c4440ec0cbe3130da08c9e6e774.png)

I'm not sure if this belongs here, but I could not find any answers. If I should change settings or mess with a certain file please let me know.
```

2. Editing `config.toml`.

> config.toml

```md
BaseUrl= "http://path/hugo-theme-air"
LanguageCode= "en-US"
Title= "my blog"
paginate = 5
DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2015"
canonifyurls = true

[params]
  #description = "this is my description"
  cover = "images/cover.jpg"
  author = "lowpro"
  authorlocation = "Japan"
  authorwebsite = "https://syui.github.io"
  #bio= "my bio"
  #logo = "images/phoenix_world.png"
  #googleAnalyticsUserID = "UA-64985747-4"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feedly.com/i/subscription/feed/https://syui.github.io/atom.xml"
  #githubName = "syui"
  #twitterName = "syui__"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
```

3. run command `$ hugo server`.

```bash
$ pwd
hugo-theme-air

$ hugo server
```

**Comment by lowpro** [comment]
Thank you! I found out I was only compiling the blog and not the theme at all, since hugo was not in the themes\hugo-air-theme folder. It works now :+1:
