### ISSUE TITLE
some advices

### ISSUE THREAD

**Issue by QuakeWang** [syui/hugo-theme-air#20]
hello，I have used hugo-theme-air as my blog theme. But when I used it, I found that the articles are arranged in order, not in the form of a title. This is not convenient for finding articles. If possible, I hope it can be changed. thanks

**Comment by syui** [comment]
Do you mean to order them by title instead of by date?

Take a look at the `.Site.RegularPages` in `layouts/index.html`.

**Comment by QuakeWang** [comment]
yeah，I found  `.Site.RegularPages `, so what should I do next??

**Comment by syui** [comment]
You might want to use `{{ range .Pages.ByTitle }}}`.

https://gohugo.io/templates/lists/

**Comment by QuakeWang** [comment]
I have found layouts/_default/list.html , so should I add `{{ range .Pages.ByTitle }}}` in the index.html, or create a new file to write `{{ range .Pages.ByTitle }}}`??

**Comment by syui** [comment]
rewrite `layout/index.html`

### befor

```html
{{ range $index, $page := $paginator.Pages }}
  {{ .Render "li" }}
{{ end }}
```

### after

```html
{{ range .Site.RegularPages.ByTitle }}
  {{ .Render "li"}}
{{ end }}
```
