### ISSUE TITLE
Particle files

### ISSUE THREAD

**Issue by hanu7674** [syui/hugo-theme-air#21]
how to use particles in my hugo theme...i need some help to use particle-js in my webpage...help me

**Comment by syui** [comment]
Can I help you with something?

**Comment by syui** [comment]
I also use particle-js here. Please try to reference.

https://github.com/syui/syui.github.io/blob/src/layouts/nyancat/single.html

demo : https://syui.cf/nyancat

After setting particles-js here, download it and use it.

https://vincentgarreau.com/particles.js/

**Comment by syui** [comment]
https://github.com/samrobbins85/hugo-developer-portfolio/blob/master/layouts/partials/head.html

```html
<div id="particles-js"></div>
<script src="particles.js"></script>
```

add `static/assets/particles.js`, `static/particles.js`

You may need to adjust css.

**Comment by syui** [comment]
ref : https://github.com/syui/syui.github.io/blob/src/layouts/nyancat/single.html#L36-L38

**Comment by hanu7674** [comment]
im using cdn for the particles.js

**Comment by hanu7674** [comment]
<script src="https://www.jsdelivr.com/package/npm/particles.js@2.0.0/particles.min.js" defer></script>

**Comment by syui** [comment]
Please confirm by browser verification whether it is loaded normally.

**Comment by hanu7674** [comment]
i checked it normally outside the hugo server then also it cant show anything only flat coloured page...is it browser or os problem..?

**Comment by syui** [comment]
For a preview, try downloading the file locally and running it.

**Comment by hanu7674** [comment]
i tried it bro but i couldn't get webpage

**Comment by syui** [comment]
Please refer to here and incorporate it into hugo. 

https://github.com/VincentGarreau/particles.js/tree/master/demo

Further advice is difficult.

**Comment by syui** [comment]
Try previewing something simple at first.

**Comment by hanu7674** [comment]
demo is working bro but how to use the particle-js for hugo-developer-portfolio
 
how can i integrate both can you expalin a bit more  and clear

**Comment by syui** [comment]
Please refer to index.html after placing necessary files in static.

https://github.com/VincentGarreau/particles.js/blob/master/demo/index.html

**Comment by hanu7674** [comment]
could you please set it up for me.....

**Comment by syui** [comment]
No, It's not my place to do it.
