### ISSUE TITLE
cover image does not display

### ISSUE THREAD

**Issue by Haggle1996** [syui/hugo-theme-air#5]
On any browser, visiting your demo site at http://syui.github.io/hugo-theme-air/ or the site when installed locally, the cover image doesn't display, leaving a blue background (images/cover.jpg). The image is available at the specified url.

**Comment by Haggle1996** [comment]
Commenting out [this](https://github.com/syui/hugo-theme-air/blob/master/static/css/screen.css#L1994) line resolves the issue.

**Comment by syui** [comment]
The reason for comment out : It is slow display speed.

**Comment by syui** [comment]
@Haggle1996 Thx, It will help to solve the problem.
