### ISSUE TITLE
The theme of the blog has no pages, post and also author details.

### ISSUE THREAD

**Issue by englianhu** [syui/hugo-theme-air#6]
I tried to create my own Hugo blog by apply your theme. However there has only page which has no any post and pages but also the blog's author. Kindly look into this?
- [My Hugo Blog](http://englianhu.github.io/)
- [englianhu.github.io Source Code](https://github.com/englianhu/englianhu.github.io)
- [Hugo Blog Source Code](https://github.com/englianhu/ryoeng)

Reference :
- [使用hugo搭建个人博客站点](http://blog.coderzh.com/2015/08/29/hugo/)
- [利用 Hugo & GitHub 搭建个人博客静态网站](http://blog.bpcoder.com/2015/12/hugo-create-blog/)
- [AIR theme for hugo](https://github.com/syui/hugo-theme-air)
- [WHOIS](https://whois.domaintools.com/)
- [Hugo-Theme-Air-Demo](http://syui.github.io/hugo-theme-air/)

**Comment by syui** [comment]
Thank you. I do not know well, has been changed a little code.

**Comment by englianhu** [comment]
😅 Kindly take a look if anything wrong with my codes since you are the author which will know if your theme is working fine?

**Comment by syui** [comment]
No

**Comment by englianhu** [comment]
@syui 不能帮忙瞧瞧嚒？其它主题都没问题啊！
https://disqus.com/home/discussion/imeoer/an_elegant_static_blog_generator_inkpaper_71/#comment-2466744742

**Comment by syui** [comment]
Okay, thanks.

**Comment by englianhu** [comment]
问题出现在哪儿呢？多了只小鸟，蜘蛛网却不见了？然后看不到部落格作者资料和页面是1/0...没有任何页面。
http://englianhu.github.io/

![capture](https://cloud.githubusercontent.com/assets/7227582/13322284/1dda6036-dc17-11e5-9d0d-c709accaf9b8.JPG)

**Comment by syui** [comment]
It sends a Pull Request.
