### ISSUE TITLE
I have no idea how to make a menu appear. Also, can I limit posts to show summary on home?

### ISSUE THREAD

**Issue by syui** [syui/hugo-theme-air#7]
https://twitter.com/gaetawoo/status/883831964498898945

### make a menu appear.

edit `hugo-theme-air/layouts/index.html`
 
```js
// comment delete
{{ if .Site.Menus.main }}
.
.
.
```

or please refer

https://github.com/syui/hugo-theme-wave

### limit posts to show summary on home

```bash
$ cp hugo-theme-air/layouts/partials/header.html hugo-theme-air/layouts/partials/header_post.html

$ edit hugo-theme-air/layouts/partials/header_post.html
- <div id="particles-js"></div>
- <script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
- <script src="{{ .Site.BaseURL }}js/particles.js"></script>   

$ edit hugo-theme-air/layouts/_default/single.html
-  {{ partial "header.html" . }}
+ {{ partial "header_post.html" . }}
```

### example

branch : sample1

```bash
$ git clone https://github.com/syui/hugo-theme-air
$ cd hugo-theme-air
$ git checkout sample1
$ hugo server
```

**Comment by gaetawoo** [comment]
@syui 
Thank you for your reply, it's very kind for you to help me!

For the menu:
Now the menu button works (it opens and closes) but the menu itself doesn't appear with anything inside of it. See the attached screen capture. I have an about page that has the correct front matter of  `menu = "main"` but as you can see, it doesn't show anything, including the RSS subscribe button.

If i go to the /layouts/partials/navigation.html and delete the comments, then the links for About page and Subscribe will work but you can't see them (they are invisible, probably behind the graphic) and the menu button no longer opens and closes. So I'm not sure how to make it both work.

![capture](https://user-images.githubusercontent.com/5017089/27990572-c09267aa-6420-11e7-872e-2b5c04e649e5.PNG)


For the post summary:
Thank you for helping with that, I wasn't meaning to remove the header graphic but it is helpful to know how to do that. What I did want was a Read More button in the main page with all the posts... Because without it, the entire post shows up on the front page. I just want a part of the post to show up. So I actually found the {{ .Summary }} section in the li.html file and removed the comment, and then it worked as I wanted it.

Again, thank you for your help! What do you think is wrong with the menu? I haven't overridden any of your theme templates so it's not that.
-Jeremiah

**Comment by syui** [comment]
@gaetawoo 

### example

> $ edit `layouts/partials/navigation.html`


css menu : https://github.com/balzss/luxbar

```html
<link rel="stylesheet" href="https://cdn.rawgit.com/balzss/luxbar/ae5835e2/build/luxbar.min.css">
<div class="luxbar luxbar-static">
    <input type="checkbox" id="luxbar-checkbox" class="luxbar-checkbox">
    <div class="luxbar-menu luxbar-menu-right luxbar-menu-dark">
        <ul class="luxbar-navigation">
            <li class="luxbar-header">
                <a class="luxbar-brand" href="#">Brand</a>
                <label class="luxbar-hamburger luxbar-hamburger-doublespin"
                        for="luxbar-checkbox"> <span></span> </label>
            </li>
            <li class="luxbar-item active"><a href="#">Home</a></li>
            <li class="luxbar-item dropdown"><a href="#">Users</a>
                <ul>
                    <li class="luxbar-item" ><a href="#">Max</a></li>
                    <li class="luxbar-item" ><a href="#">Edgar</a></li>
                    <li class="luxbar-item" ><a href="#">John</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

<!--
<div class="nav">
    <h3 class="nav-title">Menu</h3>
    <a href="#" class="nav-close">
        <span class="hidden">Close</span>
    </a>
    <ul>
        {{ $currentNode := . }}
        {{ range .Site.Menus.main }}
            {{.Pre}}
            <li class="nav-opened{{if $currentNode.IsMenuCurrent "main" . }} nav-current{{end}}" role="presentation">
            	<a href="{{.URL}}">{{.Name}}</a>
            </li>
            <li class="nav-opened{{if $currentNode.IsMenuCurrent "main" . }} nav-current{{end}}" role="presentation">
            	<a href="{{.URL}}">{{.Name}}</a>
            </li>
        {{end}}
    </ul>
    
    {{ if .Site.Params.RSSLink}}
    <a class="subscribe-button icon-feed" href="{{.Site.Params.RSSLink }}">Subscribe</a> </div>
    {{else}}
    <a class="subscribe-button icon-feed" href="{{if .IsNode}}{{.RSSLink}}{{else}}{{ .Site.BaseURL }}index.xml{{end}}">Subscribe</a>
    {{end}}
</div>
<span class="nav-cover"></span>
-->
```

> $ edit `layouts/index.html`

```html
{{ partial "header.html" . }}

{{if .Site.Params.cover}}
<header class="main-header " style="background-image: url({{.Site.BaseURL}}{{.Site.Params.cover}})">

{{else}}
<header class="main-header no-cover">
{{end}}
    

    <nav class="main-nav overlay clearfix">
        {{ if .Site.Params.logo }}
            <a class="blog-logo" href="{{ .Permalink }}"><img src="{{ .Site.BaseURL }}{{.Site.Params.logo}}" alt="Blog Logo" /></a>
        {{end}}
{{ partial "navigation.html" . }}
<!--
        {{ if .Site.Menus.main }}
            <a class="menu-button" href="#"><span class="burger">&#9776;</span><span class="word">Menu</span></a>
        {{else}}
            {{ if .Site.Params.RSSLink}}
              <a class="menu-button icon-feed" href="{{.Site.Params.RSSLink }}">&nbsp;&nbsp;Subscribe</a>
            {{else}}
              <a class="menu-button icon-feed" href="{{ .RSSLink }}">&nbsp;&nbsp;Subscribe</a>
            {{end}}
        {{end}}
	-->

    </nav>
<div class="vertical">
        <div class="main-header-content inner">
            <h1 class="page-title">
              <a class="btn-bootstrap-2 title-scroll" href="#content">{{ .Site.Title }}</a>
          </h1>
          <h2 class="page-description">{{ .Site.Params.description }}</h2>
        </div>
</div>
    <a class="scroll-down icon-arrow-left" href="#content"><span class="hidden">Scroll Down</span></a>
</header>

<main id="content" class="content" role="main">

    {{ $paginator := .Paginate (where .Data.Pages "Section" "post") }}

    <div class="extra-pagination inner">
        {{ partial "pagination.html" $paginator }}
    </div>

    {{ range $index, $page := $paginator.Pages }}
        {{ .Render "li" }}
    {{ end }}

    {{ partial "pagination.html" $paginator }}

</main>

{{ partial "footer.html" . }}
```

**Comment by syui** [comment]
```bash
$ git checkout sample1
$ git pull
```

**Comment by syui** [comment]
> For the menu

I believe so, edit `L541 : static/css/screen.css`

**Comment by gaetawoo** [comment]
Thank you for the suggestions and the help. With them, I've been able to modify my files/menu/css to get the theme working as I would like. Thank you very much for your help!

**Comment by paskal** [comment]
It would be nice to switch site to show summary without modifying source code, via some option. For example, don't truncate long posts but obey ```<!--more-->```, e.g. when author explicitly cut the post into summary and full text.

**Comment by biooo** [comment]
Hi I also tested this navigation bar. If you click the menu and go to second page, the navigation bar will heavily cover the header of the linked page (see image enclosed). It does not seem to be a good solution. Any suggestion. Thanks.

![Uploading Screen Shot 2019-02-24 at 21.16.28.png…]()

**Comment by biooo** [comment]
Many thanks for your update, Syui. It now works. However, several problems came out. 
1) If you click "About" and go to the next page, the navigation bar will become the same as your orignal setting (see image enclosed). 
![screen shot 2019-02-25 at 22 33 47](https://user-images.githubusercontent.com/38316570/53373490-89e10000-394d-11e9-9c7b-1fe10195eb98.png)

2) If you click Home while on the page of "about", it would not bring you back to the main page.

**Comment by syui** [comment]
There is a problem of hugo.

and Please use secret mode of browser.

```sh
$ hugo server
C+c
$ hugo build
$ hugo server
```
