### ISSUE TITLE
Errors on site without expected parameters set

### ISSUE THREAD

**Issue by paskal** [syui/hugo-theme-air#9]
Hello!

$subj, when trying to run this theme against my [blog](https://github.com/paskal/terrty/tree/master/blog) source I get following:

```
Building sites … ERROR 2018/03/20 10:37:14 Error while rendering "page" in "post/": template: theme/_default/single.html:66:7: executing "theme/_default/single.html" at <partial "author.html...>: error calling partial: template: theme/partials/author.html:2:13: executing "theme/partials/author.html" at <index .Site.Data.aut...>: error calling index: value is nil; should be of type string
ERROR 2018/03/20 10:37:14 Error while rendering "page" in "": template: theme/_default/single.html:66:7: executing "theme/_default/single.html" at <partial "author.html...>: error calling partial: template: theme/partials/author.html:2:13: executing "theme/partials/author.html" at <index .Site.Data.aut...>: error calling index: value is nil; should be of type string
```

The reason is some absent `.Site.` parameters but you can't tell it for sure from error message, I guess input parameters handling could be improved.

**Comment by syui** [comment]
@paskal 

please tell me `hugo version` 

```
$ hugo version
```

**Comment by paskal** [comment]
`Hugo Static Site Generator v0.37 linux/amd64 BuildDate: 2018-02-27T09:15:25Z`

**Comment by syui** [comment]
@paskal 
I was hugo 0.38 and there was no problem.

`Hugo Static Site Generator v0.38-DEV darwin/amd64 BuildDate:`

Deleting the following part may work well.

> ./layouts/_default/single.html

```
{{.Site.Params.author}}'s Picture

or 

    {{if .Site.Params.logo}}
    <figure class="author-image">
        <a class="img" href="{{.Site.BaseURL}}" style="background-image: url({{ $baseurl }}{{.Site.Params.logo}})"><span class="hidden">{{.Site.Params.author}}'s Picture</span></a>
    </figure>
    {{end}}

    {{ partial "author.html" . }}
```

**Comment by syui** [comment]
Please try the following procedure.

```html
$ git clone https://github.com/syui/hugo-theme-air
$ cd hugo-theme-air
$ hugo
$ hugo server
open browser `http://localhost:1313`
```

**Comment by paskal** [comment]
It works the way you wrote. As I wrote initially, problem is not with example site not working - there is a problem when I run my source code against this theme and instead of properly handling absence of `Site.Data.aut...` (which is usually located in root, not in `Data`) it throws an error message.
Obvious workaround is to add this parameter to my config, but from my POV the situation could be improved on the theme side as well.

**Comment by syui** [comment]
Oh, I get it.
